# Generated by Django 5.0.2 on 2024-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_stock_last_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_close',
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
